/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

fun main() {
    val a = 16.0
    val b = -3.0
    val c = 2.0

    if (a == 0.0) {
        println("El coeficiente 'a' no puede ser cero en una función cuadrática.")
        return
    }

    println("La función cuadrática es: ${FormatoFuncion(a, b, c)}")
}


fun FormatoFuncion(a: Double, b: Double, c: Double): String {
    return "${a}x² ${if (b >= 0) "+ $b" else "- ${-b}"}x ${if (c >= 0) "+ $c" else "- ${-c}"}"
}
